### PR TITLE
TST: also run the code in "pass"

### PR DESCRIPTION
**Pull request by person142**
It seems fair that the code in pass should also run; i.e. that
directory shouldn't contain mypy false positives. Add a test that runs
the modules in that directory and fix the resulting runtime errors.

### CODE REVIEW

**Comment by person142** [comment]
Some of the failures are expected in that they are places where the stubs are not get good enough to catch the issue, but some of these might merit issues being opened.

Hm and CI is failing on Python 3.7 only; that's interesting.

**Comment by person142** [comment]
Ok, on 3.7 CI was running NumPy 1.14.2 which is what was causing the failures. I went ahead and bumped the minimum version to 1.16.0; that still goes 3 releases back (soon to be 4), so should be fine I think.

**Comment by person142** [comment]
Fixes for some of the things addressed in this PR have been merged now, so rebased to include them.

**Comment by rgommers** [comment]
Merged, thanks @person142

**Pull request merged**
