### PR TITLE
Support comparison operators for dtype

### PR DESCRIPTION
**Pull request by unnonouno**
I sometimes want to check `dtype` like this: 
```
assert x.dtype == "f"
```

Based on the source code, all comparison operators support `DtypeLike`.
https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/descriptor.c#L3167

### CODE REVIEW

**Comment by unnonouno** [comment]
Thank you for a comment. Sure. I'll add some tests to `simple.py` and check the test.

**Comment by unnonouno** [comment]
I wrote brief test cases which covers all comparison operators. Is it enough? I also can check all combination of operators and types in dtypelike (too much?).

**Comment by person142** [comment]
Thanks @unnonouno.

**Comment by unnonouno** [comment]
Thank you!!

**Pull request merged**
